catalog/config/routes.rb
Rails.application.routes.draw do
  get 'companies/import', to: 'companies#import'
  resources :companies

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

catalog/app/models/company.rb
class Company
  include Mongoid::Document
  field :company_name, type: String
  field :company_number, type: String
  field :reg_address_care_of, type: String
  field :reg_address_po_box, type: String
  field :reg_address_address_line1, type: String
  field :reg_address_address_line2, type: String
  field :reg_address_post_town, type: String
  field :reg_address_county, type: String
  field :reg_address_country, type: String
  field :reg_address_post_code, type: String
  field :company_category, type: String
  field :company_status, type: String
  field :country_of_origin, type: String
  field :dissolution_date, type: String
  field :incorporation_date, type: String
  field :accounts_account_ref_day, type: String
  field :accounts_account_ref_month, type: String
  field :accounts_next_due_date, type: String
  field :accounts_last_made_up_date, type: String
  field :accounts_account_category, type: String
  field :returns_next_due_date, type: String
  field :returns_last_made_up_date, type: String
  field :mortgages_num_mort_charges, type: String
  field :mortgages_num_mort_outstanding, type: String
  field :mortgages_num_mort_part_satisfied, type: String
  field :mortgages_num_mort_satisfied, type: String
  field :sic_code_sic_text_1, type: String
  field :sic_code_sic_text_2, type: String
  field :sic_code_sic_text_3, type: String
  field :sic_code_sic_text_4, type: String
  field :limited_partnerships_num_gen_partners, type: String
  field :limited_partnerships_num_lim_partners, type: String
  field :uri, type: String
  field :previous_name_1_condate, type: String
  field :previous_name_1_company_name, type: String
  field :previous_name_2_condate, type: String
  field :previous_name_2_company_name, type: String
  field :previous_name_3_condate, type: String
  field :previous_name_3_company_name, type: String
  field :previous_name_4_condate, type: String
  field :previous_name_4_company_name, type: String
  field :previous_name_5_condate, type: String
  field :previous_name_5_company_name, type: String
  field :previous_name_6_condate, type: String
  field :previous_name_6_company_name, type: String
  field :previous_name_7_condate, type: String
  field :previous_name_7_company_name, type: String
  field :previous_name_8_condate, type: String
  field :previous_name_8_company_name, type: String
  field :previous_name_9_condate, type: String
  field :previous_name_9_company_name, type: String
  field :previous_name_10_condate, type: String
  field :previous_name_10_company_name, type: String
  field :conf_stmt_next_due_date, type: String
  field :conf_stmt_last_made_up_date, type: String

  field :tags, type: Array

  index({ tags: 1 }, background: true)
  index({ company_name: 1 }, background: true)
end

catalog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

catalog/app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: ENV['BNAME'], password: ENV['BPASS']

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all.page params[:page]
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /companies/import
  def import
    ImportCompaniesJob.perform_later
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_company
    @company = Company.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def company_params
    params.require(:company).permit(:company_name, :company_number, :reg_address_care_of, :reg_address_po_box, :reg_address_address_line1, :reg_address_address_line2, :reg_address_post_town, :reg_address_county, :reg_address_country, :reg_address_post_code, :company_category, :company_status, :country_of_origin, :dissolution_date, :incorporation_date, :accounts_account_ref_day, :accounts_account_ref_month, :accounts_next_due_date, :accounts_last_made_up_date, :accounts_account_category, :returns_next_due_date, :returns_last_made_up_date, :mortgages_num_mort_charges, :mortgages_num_mort_outstanding, :mortgages_num_mort_part_satisfied, :mortgages_num_mort_satisfied, :sic_code_sic_text_1, :sic_code_sic_text_2, :sic_code_sic_text_3, :sic_code_sic_text_4, :limited_partnerships_num_gen_partners, :limited_partnerships_num_lim_partners, :uri, :previous_name_1_condate, :previous_name_1_company_name, :previous_name_2_condate, :previous_name_2_company_name, :previous_name_3_condate, :previous_name_3_company_name, :previous_name_4_condate, :previous_name_4_company_name, :previous_name_5_condate, :previous_name_5_company_name, :previous_name_6_condate, :previous_name_6_company_name, :previous_name_7_condate, :previous_name_7_company_name, :previous_name_8_condate, :previous_name_8_company_name, :previous_name_9_condate, :previous_name_9_company_name, :previous_name_10_condate, :previous_name_10_company_name, :conf_stmt_next_due_date, :conf_stmt_last_made_up_date)
  end
end

catalog/app/helpers/application_helper.rb
module ApplicationHelper
end

catalog/app/helpers/companies_helper.rb
module CompaniesHelper
end

catalog/app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company_name %>
    <%= form.text_field :company_name %>
  </div>

  <div class="field">
    <%= form.label :company_number %>
    <%= form.text_field :company_number %>
  </div>

  <div class="field">
    <%= form.label :reg_address_care_of %>
    <%= form.text_field :reg_address_care_of %>
  </div>

  <div class="field">
    <%= form.label :reg_address_po_box %>
    <%= form.text_field :reg_address_po_box %>
  </div>

  <div class="field">
    <%= form.label :reg_address_address_line1 %>
    <%= form.text_field :reg_address_address_line1 %>
  </div>

  <div class="field">
    <%= form.label :reg_address_address_line2 %>
    <%= form.text_field :reg_address_address_line2 %>
  </div>

  <div class="field">
    <%= form.label :reg_address_post_town %>
    <%= form.text_field :reg_address_post_town %>
  </div>

  <div class="field">
    <%= form.label :reg_address_county %>
    <%= form.text_field :reg_address_county %>
  </div>

  <div class="field">
    <%= form.label :reg_address_country %>
    <%= form.text_field :reg_address_country %>
  </div>

  <div class="field">
    <%= form.label :reg_address_post_code %>
    <%= form.text_field :reg_address_post_code %>
  </div>

  <div class="field">
    <%= form.label :company_category %>
    <%= form.text_field :company_category %>
  </div>

  <div class="field">
    <%= form.label :company_status %>
    <%= form.text_field :company_status %>
  </div>

  <div class="field">
    <%= form.label :country_of_origin %>
    <%= form.text_field :country_of_origin %>
  </div>

  <div class="field">
    <%= form.label :dissolution_date %>
    <%= form.text_field :dissolution_date %>
  </div>

  <div class="field">
    <%= form.label :incorporation_date %>
    <%= form.text_field :incorporation_date %>
  </div>

  <div class="field">
    <%= form.label :accounts_account_ref_day %>
    <%= form.text_field :accounts_account_ref_day %>
  </div>

  <div class="field">
    <%= form.label :accounts_account_ref_month %>
    <%= form.text_field :accounts_account_ref_month %>
  </div>

  <div class="field">
    <%= form.label :accounts_next_due_date %>
    <%= form.text_field :accounts_next_due_date %>
  </div>

  <div class="field">
    <%= form.label :accounts_last_made_up_date %>
    <%= form.text_field :accounts_last_made_up_date %>
  </div>

  <div class="field">
    <%= form.label :accounts_account_category %>
    <%= form.text_field :accounts_account_category %>
  </div>

  <div class="field">
    <%= form.label :returns_next_due_date %>
    <%= form.text_field :returns_next_due_date %>
  </div>

  <div class="field">
    <%= form.label :returns_last_made_up_date %>
    <%= form.text_field :returns_last_made_up_date %>
  </div>

  <div class="field">
    <%= form.label :mortgages_num_mort_charges %>
    <%= form.text_field :mortgages_num_mort_charges %>
  </div>

  <div class="field">
    <%= form.label :mortgages_num_mort_outstanding %>
    <%= form.text_field :mortgages_num_mort_outstanding %>
  </div>

  <div class="field">
    <%= form.label :mortgages_num_mort_part_satisfied %>
    <%= form.text_field :mortgages_num_mort_part_satisfied %>
  </div>

  <div class="field">
    <%= form.label :mortgages_num_mort_satisfied %>
    <%= form.text_field :mortgages_num_mort_satisfied %>
  </div>

  <div class="field">
    <%= form.label :sic_code_sic_text_1 %>
    <%= form.text_field :sic_code_sic_text_1 %>
  </div>

  <div class="field">
    <%= form.label :sic_code_sic_text_2 %>
    <%= form.text_field :sic_code_sic_text_2 %>
  </div>

  <div class="field">
    <%= form.label :sic_code_sic_text_3 %>
    <%= form.text_field :sic_code_sic_text_3 %>
  </div>

  <div class="field">
    <%= form.label :sic_code_sic_text_4 %>
    <%= form.text_field :sic_code_sic_text_4 %>
  </div>

  <div class="field">
    <%= form.label :limited_partnerships_num_gen_partners %>
    <%= form.text_field :limited_partnerships_num_gen_partners %>
  </div>

  <div class="field">
    <%= form.label :limited_partnerships_num_lim_partners %>
    <%= form.text_field :limited_partnerships_num_lim_partners %>
  </div>

  <div class="field">
    <%= form.label :uri %>
    <%= form.text_field :uri %>
  </div>

  <div class="field">
    <%= form.label :previous_name_1_condate %>
    <%= form.text_field :previous_name_1_condate %>
  </div>

  <div class="field">
    <%= form.label :previous_name_1_company_name %>
    <%= form.text_field :previous_name_1_company_name %>
  </div>

  <div class="field">
    <%= form.label :previous_name_2_condate %>
    <%= form.text_field :previous_name_2_condate %>
  </div>

  <div class="field">
    <%= form.label :previous_name_2_company_name %>
    <%= form.text_field :previous_name_2_company_name %>
  </div>

  <div class="field">
    <%= form.label :previous_name_3_condate %>
    <%= form.text_field :previous_name_3_condate %>
  </div>

  <div class="field">
    <%= form.label :previous_name_3_company_name %>
    <%= form.text_field :previous_name_3_company_name %>
  </div>

  <div class="field">
    <%= form.label :previous_name_4_condate %>
    <%= form.text_field :previous_name_4_condate %>
  </div>

  <div class="field">
    <%= form.label :previous_name_4_company_name %>
    <%= form.text_field :previous_name_4_company_name %>
  </div>

  <div class="field">
    <%= form.label :previous_name_5_condate %>
    <%= form.text_field :previous_name_5_condate %>
  </div>

  <div class="field">
    <%= form.label :previous_name_5_company_name %>
    <%= form.text_field :previous_name_5_company_name %>
  </div>

  <div class="field">
    <%= form.label :previous_name_6_condate %>
    <%= form.text_field :previous_name_6_condate %>
  </div>

  <div class="field">
    <%= form.label :previous_name_6_company_name %>
    <%= form.text_field :previous_name_6_company_name %>
  </div>

  <div class="field">
    <%= form.label :previous_name_7_condate %>
    <%= form.text_field :previous_name_7_condate %>
  </div>

  <div class="field">
    <%= form.label :previous_name_7_company_name %>
    <%= form.text_field :previous_name_7_company_name %>
  </div>

  <div class="field">
    <%= form.label :previous_name_8_condate %>
    <%= form.text_field :previous_name_8_condate %>
  </div>

  <div class="field">
    <%= form.label :previous_name_8_company_name %>
    <%= form.text_field :previous_name_8_company_name %>
  </div>

  <div class="field">
    <%= form.label :previous_name_9_condate %>
    <%= form.text_field :previous_name_9_condate %>
  </div>

  <div class="field">
    <%= form.label :previous_name_9_company_name %>
    <%= form.text_field :previous_name_9_company_name %>
  </div>

  <div class="field">
    <%= form.label :previous_name_10_condate %>
    <%= form.text_field :previous_name_10_condate %>
  </div>

  <div class="field">
    <%= form.label :previous_name_10_company_name %>
    <%= form.text_field :previous_name_10_company_name %>
  </div>

  <div class="field">
    <%= form.label :conf_stmt_next_due_date %>
    <%= form.text_field :conf_stmt_next_due_date %>
  </div>

  <div class="field">
    <%= form.label :conf_stmt_last_made_up_date %>
    <%= form.text_field :conf_stmt_last_made_up_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

catalog/app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

catalog/app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Company name</th>
      <th>Company number</th>
      <th>Reg address care of</th>
      <th>Reg address po box</th>
      <th>Reg address address line1</th>
      <th>Reg address address line2</th>
      <th>Reg address post town</th>
      <th>Reg address county</th>
      <th>Reg address country</th>
      <th>Reg address post code</th>
      <th>Company category</th>
      <th>Company status</th>
      <th>Country of origin</th>
      <th>Dissolution date</th>
      <th>Incorporation date</th>
      <th>Accounts account ref day</th>
      <th>Accounts account ref month</th>
      <th>Accounts next due date</th>
      <th>Accounts last made up date</th>
      <th>Accounts account category</th>
      <th>Returns next due date</th>
      <th>Returns last made up date</th>
      <th>Mortgages num mort charges</th>
      <th>Mortgages num mort outstanding</th>
      <th>Mortgages num mort part satisfied</th>
      <th>Mortgages num mort satisfied</th>
      <th>Sic code sic text 1</th>
      <th>Sic code sic text 2</th>
      <th>Sic code sic text 3</th>
      <th>Sic code sic text 4</th>
      <th>Limited partnerships num gen partners</th>
      <th>Limited partnerships num lim partners</th>
      <th>Uri</th>
      <th>Previous name 1 condate</th>
      <th>Previous name 1 company name</th>
      <th>Previous name 2 condate</th>
      <th>Previous name 2 company name</th>
      <th>Previous name 3 condate</th>
      <th>Previous name 3 company name</th>
      <th>Previous name 4 condate</th>
      <th>Previous name 4 company name</th>
      <th>Previous name 5 condate</th>
      <th>Previous name 5 company name</th>
      <th>Previous name 6 condate</th>
      <th>Previous name 6 company name</th>
      <th>Previous name 7 condate</th>
      <th>Previous name 7 company name</th>
      <th>Previous name 8 condate</th>
      <th>Previous name 8 company name</th>
      <th>Previous name 9 condate</th>
      <th>Previous name 9 company name</th>
      <th>Previous name 10 condate</th>
      <th>Previous name 10 company name</th>
      <th>Conf stmt next due date</th>
      <th>Conf stmt last made up date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.company_name %></td>
        <td><%= company.company_number %></td>
        <td><%= company.reg_address_care_of %></td>
        <td><%= company.reg_address_po_box %></td>
        <td><%= company.reg_address_address_line1 %></td>
        <td><%= company.reg_address_address_line2 %></td>
        <td><%= company.reg_address_post_town %></td>
        <td><%= company.reg_address_county %></td>
        <td><%= company.reg_address_country %></td>
        <td><%= company.reg_address_post_code %></td>
        <td><%= company.company_category %></td>
        <td><%= company.company_status %></td>
        <td><%= company.country_of_origin %></td>
        <td><%= company.dissolution_date %></td>
        <td><%= company.incorporation_date %></td>
        <td><%= company.accounts_account_ref_day %></td>
        <td><%= company.accounts_account_ref_month %></td>
        <td><%= company.accounts_next_due_date %></td>
        <td><%= company.accounts_last_made_up_date %></td>
        <td><%= company.accounts_account_category %></td>
        <td><%= company.returns_next_due_date %></td>
        <td><%= company.returns_last_made_up_date %></td>
        <td><%= company.mortgages_num_mort_charges %></td>
        <td><%= company.mortgages_num_mort_outstanding %></td>
        <td><%= company.mortgages_num_mort_part_satisfied %></td>
        <td><%= company.mortgages_num_mort_satisfied %></td>
        <td><%= company.sic_code_sic_text_1 %></td>
        <td><%= company.sic_code_sic_text_2 %></td>
        <td><%= company.sic_code_sic_text_3 %></td>
        <td><%= company.sic_code_sic_text_4 %></td>
        <td><%= company.limited_partnerships_num_gen_partners %></td>
        <td><%= company.limited_partnerships_num_lim_partners %></td>
        <td><%= company.uri %></td>
        <td><%= company.previous_name_1_condate %></td>
        <td><%= company.previous_name_1_company_name %></td>
        <td><%= company.previous_name_2_condate %></td>
        <td><%= company.previous_name_2_company_name %></td>
        <td><%= company.previous_name_3_condate %></td>
        <td><%= company.previous_name_3_company_name %></td>
        <td><%= company.previous_name_4_condate %></td>
        <td><%= company.previous_name_4_company_name %></td>
        <td><%= company.previous_name_5_condate %></td>
        <td><%= company.previous_name_5_company_name %></td>
        <td><%= company.previous_name_6_condate %></td>
        <td><%= company.previous_name_6_company_name %></td>
        <td><%= company.previous_name_7_condate %></td>
        <td><%= company.previous_name_7_company_name %></td>
        <td><%= company.previous_name_8_condate %></td>
        <td><%= company.previous_name_8_company_name %></td>
        <td><%= company.previous_name_9_condate %></td>
        <td><%= company.previous_name_9_company_name %></td>
        <td><%= company.previous_name_10_condate %></td>
        <td><%= company.previous_name_10_company_name %></td>
        <td><%= company.conf_stmt_next_due_date %></td>
        <td><%= company.conf_stmt_last_made_up_date %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= paginate @companies %>

<br>

<%= link_to 'New Company', new_company_path %>

catalog/app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

catalog/app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company name:</strong>
  <%= @company.company_name %>
</p>

<p>
  <strong>Company number:</strong>
  <%= @company.company_number %>
</p>

<p>
  <strong>Reg address care of:</strong>
  <%= @company.reg_address_care_of %>
</p>

<p>
  <strong>Reg address po box:</strong>
  <%= @company.reg_address_po_box %>
</p>

<p>
  <strong>Reg address address line1:</strong>
  <%= @company.reg_address_address_line1 %>
</p>

<p>
  <strong>Reg address address line2:</strong>
  <%= @company.reg_address_address_line2 %>
</p>

<p>
  <strong>Reg address post town:</strong>
  <%= @company.reg_address_post_town %>
</p>

<p>
  <strong>Reg address county:</strong>
  <%= @company.reg_address_county %>
</p>

<p>
  <strong>Reg address country:</strong>
  <%= @company.reg_address_country %>
</p>

<p>
  <strong>Reg address post code:</strong>
  <%= @company.reg_address_post_code %>
</p>

<p>
  <strong>Company category:</strong>
  <%= @company.company_category %>
</p>

<p>
  <strong>Company status:</strong>
  <%= @company.company_status %>
</p>

<p>
  <strong>Country of origin:</strong>
  <%= @company.country_of_origin %>
</p>

<p>
  <strong>Dissolution date:</strong>
  <%= @company.dissolution_date %>
</p>

<p>
  <strong>Incorporation date:</strong>
  <%= @company.incorporation_date %>
</p>

<p>
  <strong>Accounts account ref day:</strong>
  <%= @company.accounts_account_ref_day %>
</p>

<p>
  <strong>Accounts account ref month:</strong>
  <%= @company.accounts_account_ref_month %>
</p>

<p>
  <strong>Accounts next due date:</strong>
  <%= @company.accounts_next_due_date %>
</p>

<p>
  <strong>Accounts last made up date:</strong>
  <%= @company.accounts_last_made_up_date %>
</p>

<p>
  <strong>Accounts account category:</strong>
  <%= @company.accounts_account_category %>
</p>

<p>
  <strong>Returns next due date:</strong>
  <%= @company.returns_next_due_date %>
</p>

<p>
  <strong>Returns last made up date:</strong>
  <%= @company.returns_last_made_up_date %>
</p>

<p>
  <strong>Mortgages num mort charges:</strong>
  <%= @company.mortgages_num_mort_charges %>
</p>

<p>
  <strong>Mortgages num mort outstanding:</strong>
  <%= @company.mortgages_num_mort_outstanding %>
</p>

<p>
  <strong>Mortgages num mort part satisfied:</strong>
  <%= @company.mortgages_num_mort_part_satisfied %>
</p>

<p>
  <strong>Mortgages num mort satisfied:</strong>
  <%= @company.mortgages_num_mort_satisfied %>
</p>

<p>
  <strong>Sic code sic text 1:</strong>
  <%= @company.sic_code_sic_text_1 %>
</p>

<p>
  <strong>Sic code sic text 2:</strong>
  <%= @company.sic_code_sic_text_2 %>
</p>

<p>
  <strong>Sic code sic text 3:</strong>
  <%= @company.sic_code_sic_text_3 %>
</p>

<p>
  <strong>Sic code sic text 4:</strong>
  <%= @company.sic_code_sic_text_4 %>
</p>

<p>
  <strong>Limited partnerships num gen partners:</strong>
  <%= @company.limited_partnerships_num_gen_partners %>
</p>

<p>
  <strong>Limited partnerships num lim partners:</strong>
  <%= @company.limited_partnerships_num_lim_partners %>
</p>

<p>
  <strong>Uri:</strong>
  <%= @company.uri %>
</p>

<p>
  <strong>Previous name 1 condate:</strong>
  <%= @company.previous_name_1_condate %>
</p>

<p>
  <strong>Previous name 1 company name:</strong>
  <%= @company.previous_name_1_company_name %>
</p>

<p>
  <strong>Previous name 2 condate:</strong>
  <%= @company.previous_name_2_condate %>
</p>

<p>
  <strong>Previous name 2 company name:</strong>
  <%= @company.previous_name_2_company_name %>
</p>

<p>
  <strong>Previous name 3 condate:</strong>
  <%= @company.previous_name_3_condate %>
</p>

<p>
  <strong>Previous name 3 company name:</strong>
  <%= @company.previous_name_3_company_name %>
</p>

<p>
  <strong>Previous name 4 condate:</strong>
  <%= @company.previous_name_4_condate %>
</p>

<p>
  <strong>Previous name 4 company name:</strong>
  <%= @company.previous_name_4_company_name %>
</p>

<p>
  <strong>Previous name 5 condate:</strong>
  <%= @company.previous_name_5_condate %>
</p>

<p>
  <strong>Previous name 5 company name:</strong>
  <%= @company.previous_name_5_company_name %>
</p>

<p>
  <strong>Previous name 6 condate:</strong>
  <%= @company.previous_name_6_condate %>
</p>

<p>
  <strong>Previous name 6 company name:</strong>
  <%= @company.previous_name_6_company_name %>
</p>

<p>
  <strong>Previous name 7 condate:</strong>
  <%= @company.previous_name_7_condate %>
</p>

<p>
  <strong>Previous name 7 company name:</strong>
  <%= @company.previous_name_7_company_name %>
</p>

<p>
  <strong>Previous name 8 condate:</strong>
  <%= @company.previous_name_8_condate %>
</p>

<p>
  <strong>Previous name 8 company name:</strong>
  <%= @company.previous_name_8_company_name %>
</p>

<p>
  <strong>Previous name 9 condate:</strong>
  <%= @company.previous_name_9_condate %>
</p>

<p>
  <strong>Previous name 9 company name:</strong>
  <%= @company.previous_name_9_company_name %>
</p>

<p>
  <strong>Previous name 10 condate:</strong>
  <%= @company.previous_name_10_condate %>
</p>

<p>
  <strong>Previous name 10 company name:</strong>
  <%= @company.previous_name_10_company_name %>
</p>

<p>
  <strong>Conf stmt next due date:</strong>
  <%= @company.conf_stmt_next_due_date %>
</p>

<p>
  <strong>Conf stmt last made up date:</strong>
  <%= @company.conf_stmt_last_made_up_date %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

catalog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>